trigger:
- main

variables:
 pathToProject: './SMTC.API.TaxaJuros/SMTC.API.TaxaJuros.csproj'
 pathToTestProject: './SMTC.Tests/SMTC.Tests.csproj'
 vmImageName: ubuntu-latest

stages:
- stage: Tests
  displayName: Teste de unidade
  jobs: 
  - job: Tests
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DotNetCoreCLI@2
      displayName: Execução dos testes de Unidade
      inputs:
        command: 'test'
        projects: '$(pathToTestProject)'
- stage: Build
  dependsOn: Tests
  displayName: Build da Aplicação
  jobs: 
  - job: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DotNetCoreCLI@2
      displayName:  'Restore das dependências'
      inputs:
        command: 'restore'
        projects: '$(pathToProject)'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName:  'Compilar aplicação'
      inputs:
        command: 'build'
        projects: '$(pathToProject)'

    - task: DotNetCoreCLI@2
      displayName:  'Gerar Artefatos'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(pathToProject)'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'